<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Beaver</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Beaver.Application.Contracts\Beaver.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
