<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
		<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>

		<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.6">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.6" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.6" />
		<PackageReference Include="WalkingTec.Mvvm.Mvc" Version="6.2.9" />
		<PackageReference Include="Yarp.ReverseProxy" Version="1.1.1" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="App_Data\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MoviesLibrary\MoviesLibrary.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\font-awesome\css\font-awesome.css">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="wwwroot\layuiadmin\style\res\logo.png">
		  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <None Update="App_Data\BeaverVideos_db.db">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>

